In [46]:
import pandas as pd
import numpy as np
# To Read the dataset 
data=pd.read_csv("C:\\Users\\Saicharith\\OneDrive\\Desktop\\HRDataset_v14.csv")
data

Employee_Name  EmpID  MarriedID  MaritalStatusID  GenderID  \
0         Adinolfi, Wilson  K  10026          0                0         1   
1    Ait Sidi, Karthikeyan     10084          1                1         1   
2           Akinkuolie, Sarah  10196          1                1         0   
3                Alagbe,Trina  10088          1                1         0   
4            Anderson, Carol   10069          0                2         0   
..                        ...    ...        ...              ...       ...   
306            Woodson, Jason  10135          0                0         1   
307        Ybarra, Catherine   10301          0                0         0   
308          Zamora, Jennifer  10010          0                0         0   
309               Zhou, Julia  10043          0                0         0   
310             Zima, Colleen  10271          0                4         0   

     EmpStatusID  DeptID  PerfScoreID  FromDiversityJobFairID  Salary  ...  \
0              1       5            4                       0   62506  ...   
1              5       3            3                       0  104437  ...   
2              5       5            3                       0   64955  ...   
3              1       5            3                       0   64991  ...   
4              5       5            3                       0   50825  ...   
..           ...     ...          ...                     ...     ...  ...   
306            1       5            3                       0   65893  ...   
307            5       5            1                       0   48513  ...   
308            1       3            4                       0  220450  ...   
309            1       3            3                       0   89292  ...   
310            1       5            3                       0   45046  ...   

        ManagerName  ManagerID  RecruitmentSource PerformanceScore  \
0    Michael Albert       22.0           LinkedIn          Exceeds   
1        Simon Roup        4.0             Indeed      Fully Meets   
2    Kissy Sullivan       20.0           LinkedIn      Fully Meets   
3      Elijiah Gray       16.0             Indeed      Fully Meets   
4    Webster Butler       39.0      Google Search      Fully Meets   
..              ...        ...                ...              ...   
306  Kissy Sullivan       20.0           LinkedIn      Fully Meets   
307  Brannon Miller       12.0      Google Search              PIP   
308      Janet King        2.0  Employee Referral          Exceeds   
309      Simon Roup        4.0  Employee Referral      Fully Meets   
310   David Stanley       14.0           LinkedIn      Fully Meets   

     EngagementSurvey EmpSatisfaction SpecialProjectsCount  \
0                4.60               5                    0   
1                4.96               3                    6   
2                3.02               3                    0   
3                4.84               5                    0   
4                5.00               4                    0   
..                ...             ...                  ...   
306              4.07               4                    0   
307              3.20               2                    0   
308              4.60               5                    6   
309              5.00               3                    5   
310              4.50               5                    0   

    LastPerformanceReview_Date DaysLateLast30 Absences  
0                    1/17/2019              0        1  
1                    2/24/2016              0       17  
2                    5/15/2012              0        3  
3                     1/3/2019              0       15  
4                     2/1/2016              0        2  
..                         ...            ...      ...  
306                  2/28/2019              0       13  
307                   9/2/2015              5        4  
308                  2/21/2019             

In [47]:
#Displaying some information about HR dataset
no_of_rows,no_of_columns=data.shape
print(f"No of rows present in HR dataset: {no_of_rows}")
print(f"No of Columns present in HR dataset: {no_of_columns}")

No of rows present in HR dataset: 311
No of Columns present in HR dataset: 36


In [48]:
print("Count of duplicates: ",data.duplicated().sum())

Count of duplicates:  0


In [49]:
#checking null valued columns
data.isna().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Sex                             0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             207
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceSco

In [50]:
#poping out null valued columns
data=data.drop("DateofTermination",axis="columns")
data=data.drop("ManagerID",axis="columns")
data.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Sex', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'TermReason', 'EmploymentStatus', 'Department',
       'ManagerName', 'RecruitmentSource', 'PerformanceScore',
       'EngagementSurvey', 'EmpSatisfaction', 'SpecialProjectsCount',
       'LastPerformanceReview_Date', 'DaysLateLast30', 'Absences'],
      dtype='object')

In [51]:
#describing the data
data.describe()

EmpID   MarriedID  MaritalStatusID    GenderID  EmpStatusID  \
count    311.000000  311.000000       311.000000  311.000000   311.000000   
mean   10156.000000    0.398714         0.810289    0.434084     2.392283   
std       89.922189    0.490423         0.943239    0.496435     1.794383   
min    10001.000000    0.000000         0.000000    0.000000     1.000000   
25%    10078.500000    0.000000         0.000000    0.000000     1.000000   
50%    10156.000000    0.000000         1.000000    0.000000     1.000000   
75%    10233.500000    1.000000         1.000000    1.000000     5.000000   
max    10311.000000    1.000000         4.000000    1.000000     5.000000   

           DeptID  PerfScoreID  FromDiversityJobFairID         Salary  \
count  311.000000   311.000000              311.000000     311.000000   
mean     4.610932     2.977492                0.093248   69020.684887   
std      1.083487     0.587072                0.291248   25156.636930   
min      1.000000     1.000000                0.000000   45046.000000   
25%      5.000000     3.000000                0.000000   55501.500000   
50%      5.000000     3.000000                0.000000   62810.000000   
75%      5.000000     3.000000                0.000000   72036.000000   
max      6.000000     4.000000                1.000000  250000.000000   

            Termd  PositionID           Zip  EngagementSurvey  \
count  311.000000  311.000000    311.000000        311.000000   
mean     0.334405   16.845659   6555.482315          4.110000   
std      0.472542    6.223419  16908.396884          0.789938   
min      0.000000    1.000000   1013.000000          1.120000   
25%      0.000000   18.000000   1901.500000          3.690000   
50%      0.000000   19.000000   2132.000000          4.280000   
75%      1.000000   20.000000   2355.000000          4.700000   
max      1.000000   30.000000  98052.000000          5.000000   

       EmpSatisfaction  SpecialProjectsCount  DaysLateLast30    Absences  
count       311.000000            311.000000      311.000000  311.000000  
mean          3.890675              1.218650        0.414791   10.237942  
std           0.909241              2.349421        1.294519    5.852596  
min           1.000000              0.000000        0.000000    1.000000  
25%           3.000000              0.000000        0.000000    5.000000  
50%           4.000000              0.000000        0.000000   10.000000  
75%           5.000000              0.000000        0.000000   15.000000  
max           5.000000              8.000000        6.000000   20.000000

In [52]:
data.isna().sum()

Employee_Name                 0
EmpID                         0
MarriedID                     0
MaritalStatusID               0
GenderID                      0
EmpStatusID                   0
DeptID                        0
PerfScoreID                   0
FromDiversityJobFairID        0
Salary                        0
Termd                         0
PositionID                    0
Position                      0
State                         0
Zip                           0
DOB                           0
Sex                           0
MaritalDesc                   0
CitizenDesc                   0
HispanicLatino                0
RaceDesc                      0
DateofHire                    0
TermReason                    0
EmploymentStatus              0
Department                    0
ManagerName                   0
RecruitmentSource             0
PerformanceScore              0
EngagementSurvey              0
EmpSatisfaction               0
SpecialProjectsCount          0
LastPerf

In [53]:
target=data["Salary"]
data=data.drop("Salary",axis="columns")
data


Employee_Name  EmpID  MarriedID  MaritalStatusID  GenderID  \
0         Adinolfi, Wilson  K  10026          0                0         1   
1    Ait Sidi, Karthikeyan     10084          1                1         1   
2           Akinkuolie, Sarah  10196          1                1         0   
3                Alagbe,Trina  10088          1                1         0   
4            Anderson, Carol   10069          0                2         0   
..                        ...    ...        ...              ...       ...   
306            Woodson, Jason  10135          0                0         1   
307        Ybarra, Catherine   10301          0                0         0   
308          Zamora, Jennifer  10010          0                0         0   
309               Zhou, Julia  10043          0                0         0   
310             Zima, Colleen  10271          0                4         0   

     EmpStatusID  DeptID  PerfScoreID  FromDiversityJobFairID  Termd  ...  \
0              1       5            4                       0      0  ...   
1              5       3            3                       0      1  ...   
2              5       5            3                       0      1  ...   
3              1       5            3                       0      0  ...   
4              5       5            3                       0      1  ...   
..           ...     ...          ...                     ...    ...  ...   
306            1       5            3                       0      0  ...   
307            5       5            1                       0      1  ...   
308            1       3            4                       0      0  ...   
309            1       3            3                       0      0  ...   
310            1       5            3                       0      0  ...   

            Department     ManagerName  RecruitmentSource  PerformanceScore  \
0    Production         Michael Albert           LinkedIn           Exceeds   
1                IT/IS      Simon Roup             Indeed       Fully Meets   
2    Production         Kissy Sullivan           LinkedIn       Fully Meets   
3    Production           Elijiah Gray             Indeed       Fully Meets   
4    Production         Webster Butler      Google Search       Fully Meets   
..                 ...             ...                ...               ...   
306  Production         Kissy Sullivan           LinkedIn       Fully Meets   
307  Production         Brannon Miller      Google Search               PIP   
308              IT/IS      Janet King  Employee Referral           Exceeds   
309              IT/IS      Simon Roup  Employee Referral       Fully Meets   
310  Production          David Stanley           LinkedIn       Fully Meets   

    EngagementSurvey EmpSatisfaction SpecialProjectsCount  \
0               4.60               5                    0   
1               4.96               3                    6   
2               3.02               3                    0   
3               4.84               5                    0   
4               5.00               4                    0   
..               ...             ...                  ...   
306             4.07               4                    0   
307             3.20               2                    0   
308             4.60               5                    6   
309             5.00               3                    5   
310             4.50               5                    0   

    LastPerformanceReview_Date DaysLateLast30 Absences  
0                    1/17/2019              0        1  
1                    2/24/2016              0       17  
2                    5/15/2012              0        3  
3                     1/3/2019              0       15  
4                     2/1/2016              0        2  
..                         ...            ...      ...  
306                  2/28/2019              0       13  
307             

In [54]:
char_cols = data.dtypes.pipe(lambda x: x[x== 'object']).index
label_mapping = {}

for c in char_cols:
    data[c], label_mapping[c] = pd.factorize(data[c])
data.head(5)

Employee_Name  EmpID  MarriedID  MaritalStatusID  GenderID  EmpStatusID  \
0              0  10026          0                0         1            1   
1              1  10084          1                1         1            5   
2              2  10196          1                1         0            5   
3              3  10088          1                1         0            1   
4              4  10069          0                2         0            5   

   DeptID  PerfScoreID  FromDiversityJobFairID  Termd  ...  Department  \
0       5            4                       0      0  ...           0   
1       3            3                       0      1  ...           1   
2       5            3                       0      1  ...           0   
3       5            3                       0      0  ...           0   
4       5            3                       0      1  ...           0   

   ManagerName  RecruitmentSource  PerformanceScore  EngagementSurvey  \
0            0                  0                 0              4.60   
1            1                  1                 1              4.96   
2            2                  0                 1              3.02   
3            3                  1                 1              4.84   
4            4                  2                 1              5.00   

   EmpSatisfaction  SpecialProjectsCount  LastPerformanceReview_Date  \
0                5                     0                           0   
1                3                     6                           1   
2                3                     0                           2   
3                5                     0                           3   
4                4                     0                           4   

   DaysLateLast30  Absences  
0               0         1  
1               0        17  
2               0         3  
3               0        15  
4               0         2  

[5 rows x 33 columns]

In [60]:
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
#data = StandardScaler().fit_transform(data)

#split the data

x_train , x_test, y_train , y_test = train_test_split(data, target,test_size=0.2, shuffle=True)

clf = LogisticRegression().fit(x_train,y_train) 
pred = clf.predict(x_test)
print("Confusion Matrix:")
print(confusion_matrix(pred,y_test))
print('training complete')
print("Classification Report: ")
print(classification_report(y_test, pred))

Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
training complete
Classification Report: 
              precision    recall  f1-score   support

       46799       0.00      0.00      0.00       1.0
       46837       0.00      0.00      0.00       0.0
       47001       0.00      0.00      0.00       0.0
       47434       0.00      0.00      0.00       0.0
       47750       0.00      0.00      0.00       0.0
       47837       0.00      0.00      0.00       0.0
       48285       0.00      0.00      0.00       1.0
       48513       0.00      0.00      0.00       1.0
       48888       0.00      0.00      0.00       1.0
       49256       0.00      0.00      0.00       1.0
       49773       0.00      0.00      0.00       1.0
       50274       0.00      0.00      0.00       1.0
       50428       0.00      0.00      0.00       0.0
       50470       0.00      0.00      0.00       0.0
       51

C:\Users\Saicharith\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Saicharith\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Saicharith\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Saicharith\anaconda3\lib\site-packages\